#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/string/toUpperCase/C/SSE2_Intrinsics/0/char/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: SSE String Operations
#####################################################################

 # Kernel iterates over PROBLEMLIST
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="10000-10000000/10000"
 
 # will be used by sse-unaligned and normal execution, not by sse aligned
 BENCHIT_KERNEL_PROBLEMSIZE_OFFSET=1

