#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/matmul/F77/MPI/0/MPI_F77/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################

######################################################################
# the following lines are for the benchit-shell B-CARE		
#
#!BENCHIT_VARIABLE BENCHIT_MATMUL_F77_DOUBLE_MPI_MPIF_MAXPROBLEMSIZE 200
#!BENCHIT_VARIABLE BENCHIT_MATMUL_F77_DOUBLE_MPI_MPIF_NUM_PROC 32
######################################################################


 #################################################
 # BEGINOF matmul_f77_double_mpi_MPIF/PARAMETERS #
 #################################################

 #################################################################
 # MAXPROBLEMSIZE=maximum matrix size per processor              #
 # every processor has to multiply a result matrix with          #
 # numproz*MAXPROBLEMSIZE rows and MAXPROBLEMSIZE columns        #
 # MAXPROBLEMSIZE 20 means on 30 processors that every processor #
 # calculates a 600*20 matrix                                    #
 #################################################################
 BENCHIT_MATMUL_F77_DOUBLE_MPI_MPIF_MAXPROBLEMSIZE=600

 #############################
 # number of processors used #
 #############################
 BENCHIT_MATMUL_F77_DOUBLE_MPI_MPIF_NUM_PROC=${BENCHIT_NUM_CPUS}
 
 #################################################
 # ENDOF matmul_f77_double_mpi_MPIF/PARAMETERS #
 #################################################
