#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/gemv/C/SSE_Intrinsics/0/aligned_m128/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: C SGEMV kernel (SSE, aligned data)
#####################################################################

 # Kernel iterates over PROBLEMLIST (one dim of the squared matricies)
 # (using problemsizes, which are no multiples of 4 can lead to
 # (partial) unaligned data access)
 BENCHIT_KERNEL_PROBLEMLIST="4-600/4"

