#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/BLAS1/C/0/ATLAS/daxpy/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Measurment of daxpy performance
#####################################################################

 # Kernel iterates over PROBLEMLIST
 BENCHIT_KERNEL_PROBLEMLIST="1-5000/7"

