#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/meanSquareError/C/0/0/double/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
 
 # Kernel iterates over PROBLEMLIST (number of unknows in approximation polynom)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="1-100/1"
 
 # number of points the polynom shall fit
 # Attention: numPoints >= max(problemlist)
 BENCHIT_KERNEL_NUMPOINTS=100
 
