#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
#####################################################################

 # Maximum time a kernel may run, in seconds
 # 0 means no timelimit, and the kernel will run until all measurements have
 # completed  
 BENCHIT_RUN_TIMELIMIT=0
 
 # iRODS rescource
 # BENCHIT_IRODS_RESC="" means default resource
 BENCHIT_IRODS_RESC=""
 
 # iRODS data transfer protocol
 # 0 -> TCP; 1 -> RBUDP (iRODS version 2++)
 BENCHIT_IRODS_PROT=0
 
 # Number of threads used for data transfer
 # -1 -> automatically
 #  0 -> no threading
 # >0 -> number of threads
 BENCHIT_IRODS_THREADS=-1
 
 # Path of temporary saved files (attention to enough space)
 # $KERNELDIR -> path of this Kernel
 BENCHIT_KERNEL_PATH_TEMP=$KERNELDIR

 # Number of files transfered on iRODS with one transfer 
 BENCHIT_KERNEL_FILES_NUMBER=100
 
 # Number of transfers
 BENCHIT_KERNEL_FILL_NUMBER=4
 
 # Last file number of a previous measurement 
 # (useful if you want to continue a measurement)
 BENCHIT_KERNEL_FILES_START=0
 
 # Remove transfered files on iRODS
 #  0 -> keep transfered files 
 # >0 -> remove transfered files
 BENCHIT_KERNEL_DELETE_FILES_IRODS=0
 
 # Size of one file
 # BENCHIT_KERNEL_FILE_UNIT: "" -> Byte;"K" -> KByte;"M" -> MByte;"G"=GByte
 # BENCHIT_KERNEL_FILE_SIZE_BLOCK   -> size of one block
 # BENCHIT_KERNEL_FILE_NUMBER_BLOCK -> number of blocks
 # Example:
 # BENCHIT_KERNEL_FILE_UNIT="M",BENCHIT_KERNEL_FILE_SIZE_BLOCK=5,
 # BENCHIT_KERNEL_FILE_NUMBER_BLOCK=10 means that one file is 50 MByte
 # 
 # Attention: If the file should be above 1 GByte, use a higher block number.
 # (e.g. file size 10GB -> BENCHIT_KERNEL_FILE_UNIT="G"
 #                         BENCHIT_KERNEL_FILE_BLOCK_SIZE=1
 #                         BENCHIT_KERNEL_FILE_BLOCK_NUMBER=10)
 BENCHIT_KERNEL_FILE_UNIT=""
 BENCHIT_KERNEL_FILE_BLOCK_SIZE=10
 BENCHIT_KERNEL_FILE_BLOCK_NUMBER=1
 
 # Additional filename string 
 BENCHIT_FILENAME_COMMENT="iRODS"
 
 # Path of the tool time
 BENCHIT_TOOL_TIME=/usr/bin/time
 
 # Don't change the following parameter
 
 BENCHIT_RESULT_NAME="benchit_result_`date "+%d_%m_%Y_%H_%M_%S"`"
 BENCHIT_SPEZIAL_RESULT="$BENCHIT_KERNEL_PATH_TEMP/$BENCHIT_RESULT_NAME"
 BENCHIT_SPEZIAL_SCRIPT="$KERNELDIR/start.sh"

#####################################################################
# Log-History
#
#
#####################################################################
