#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/utilities/skeleton/Java/0/PCL/0/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: java pcl kernel skeleton
# Shellscript running java kernels
#####################################################################

 ######################################################################
 # the following lines are for the benchit-shell B-CARE
 #
 #!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_START 1
 #!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_INCREMENT 1
 #!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_STEPS 600
 ######################################################################

 ######################################
 # BEGINOF skeleton_java_pcl/PARAMETERS #
 ######################################

 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_START=1
 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_INCREMENT=1
 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_STEPS=600

