#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2011-01-27 fschmitt $
# $URL: svn+ssh://benchit@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/BLAS3/C/CUDA/CUBLAS/sgemm/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Measurement of Nvidia CUBLAS sgemm performance
#####################################################################

LD_LIBRARY_PATH=${CUDA_LIB}:$LD_LIBRARY_PATH

 # Kernel iterates over PROBLEMLIST
 BENCHIT_KERNEL_PROBLEMLIST="4096-4608/2"
