#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/communication/communicate/C/MPI/0/nonblocking/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: compare the needed time for different MPI communication methodes
#####################################################################
 
 #####
 # attention: in principle the measurment of Ibsend should only show the memory bandwidth on rank 0
 #            and NOT the communication bandwidth (it's is measured here only because of completeness)
 #####
 #####
 # left y-axis:  time per rank/send
 # right y-axis: bandwidth per rank/send
 #####
 
 # Kernel iterates over PROBLEMLIST (number of floats in the sendarray)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="1024-512000/512"
 

