#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/utilities/skeleton/ruby/0/0/0/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: ruby kernel skeleton
#####################################################################

 # minimum power of the x-axis
 BENCHIT_KERNEL_PROBLEMSIZE_MIN_POWER=0
 # maximum power of the x-axis
 BENCHIT_KERNEL_PROBLEMSIZE_MAX_POWER=16
 # x-axis logbase
 BENCHIT_KERNEL_LOGBASE=2
 # how often should a measurement be done for normalization
 BENCHIT_KERNEL_MIN_RUNTIME=0

 # number of used threads
 BENCHIT_KERNEL_MAX_THREADS=1
 # number of used processes
 BENCHIT_KERNEL_MAX_PROCESSES=1

