#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/applications/CGV/C/MPI/0/double/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Heat conduction (CG-Solver, vectorized)
#         Based on the CGV-Exmple in the Parallel Programming Workshop
#         http://www.hlrs.de/organization/par/par_prog_ws/
#         Section [42] "Laplace-Example with MPI and PETSc", and
#         http://www.hlrs.de/organization/par/par_prog_ws/practical/README.html
#         CG-Solver, vectorized - CGV.tar.gz
#         by Dr. Rolf Rabenseifner (HLRS)
#####################################################################


 # problem size
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="32-1024/32"
 
 # For large problemsizes you might have to increase MPI_GROUP_MAX
 # and/or MPI_MSGS_MAX on your system
 
 
