#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numberTheory/fibonacci/C/0/0/long/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Core for calc of Fibonacci number (iterative / recursive)
#####################################################################

 # problem sizes
 BENCHIT_KERNEL_PROBLEMLIST="1-40/1"

