#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/gemv/C/SSE2_Intrinsics/0/aligned_m128d/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: C DGEMV kernel (SSE2, aligned data)
#####################################################################

 # Kernel iterates over PROBLEMLIST (one dim of the squared matricies)
 # (using problemsizes which are no multiples of 2 will lead to unaligned
 # memory access)
 BENCHIT_KERNEL_PROBLEMLIST="2-600/2"

