#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/elementary/Java/0/0/sincostan/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Execution time of mathematical operations
#         SINUS / COSINUS / TANGENT addict to input value
#####################################################################

 # Iterate over problem size from BENCHIT_KERNEL_PROBLEMSIZE_MIN
 # to BENCHIT_KERNEL_PROBLEMSIZE_MAX, incrementing by
 # BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT with each step.

 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=360
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=1

