#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/memory/bandwidth/C/MPI/0/TeTpApBxC/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Memory Bandwidth (C)
#####################################################################


 # BENCHIT_KERNEL_MIN_ACCESS_SIZE is the minimum  
 # of accessed memory (in KByte)      
 BENCHIT_KERNEL_MIN_ACCESS_SIZE=2

 # BENCHIT_KERNEL_MAX_ACCESS_SIZE is the maximum 
 # of accessed memory (in KByte)     
 BENCHIT_KERNEL_MAX_ACCESS_SIZE=10240

 # BENCHIT_KERNEL_ACCESS_STRIDE is the stride in KByte between 
 # two measurement points                       
 BENCHIT_KERNEL_ACCESS_STRIDE=10
 

