#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/communication/latencies/C/MPI/0/pingpong/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: pairwise Send/Recv between two MPI-Prozesses
#####################################################################
 
  # number of send/recv ops per mpi-proccess-pair
 BENCHIT_KERNEL_REPETITIONS=1
 
