#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# For license details see COPYING in the package base directory
#####################################################################

#A single thread accesses the shared memory with variable stride

#Number of accesses
BENCHIT_KERNEL_STRIDELIST="1-30/1"
BENCHIT_KERNEL_ARRAYLENGTH="256"
BENCHIT_KERNEL_ITERATIONS="5"
