#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/communication/bandwidth/C/MPI/0/roundtrip/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Measure MPI bandwith for a round trip send algorithm
#####################################################################
 
 # Iterate over matrix size 
 BENCHIT_KERNEL_PROBLEMLIST="1-1000/11, 1000-10000/101, 10000-100000/1001"
 

