#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/io/mix/C/0/0/iozone/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################

 # in the src/ folder use "make" to get 
 # a list of all possible target architectures
 IOZONE_COMPILE_ARCH=linux-AMD64

 # name of the file to use
 BENCHIT_KERNEL_FILENAME="/var/tmp/iozone.out"

 # The size of the files to be written.
 # use:
 #		k .. Kb
 #		m .. Mb
 #		g .. Gb
 BENCHIT_KERNEL_FILESIZE_MIN=100m
 BENCHIT_KERNEL_FILESIZE_MAX=200m
 BENCHIT_KERNEL_FILESIZE_INCREMENT=1m
 
 # each file will be written in chuncks
 # maximum is 16384k
 # use:
 #		k .. Kb
 #		m .. Mb
 BENCHIT_KERNEL_RECORDSIZE=16384k
 
 
 #####
 # possible Feature for Version 2
 #####
 # BENCHIT_KERNEL_RECORDSIZE_MIN=512k
 # BENCHIT_KERNEL_RECORDSIZE_MAX=512k
 # BENCHIT_KERNEL_RECORDSIZE_INCREMENT=512k
 #####
 
 # file access stride in multiples of recordsize
 # iozone's default is 17
 BENCHIT_KERNEL_FILESTRIDE=17
 
 # commata-separated list of tests
 # use:
 #		0 .. write, rewrite (mandatoy for the other tests)
 #		1 .. read, reread
 #		2 .. random read/write
 #		3 .. read backwarts
 #		4 .. rewrite record
 #		5 .. stride read
 #		6 .. fwrite, frewrite
 #		7 .. fread, freread
 #		8 .. random mix
 #		9 .. pwrite, prewrite
 #	   10 .. pread, preread
 #	   11 .. pwritev, prewritev
 #	   12 .. preadv, prereadv
 ##BENCHIT_KERNEL_TESTLIST="0,1,2,3,4,5,6,7"
 BENCHIT_KERNEL_TESTLIST="0,1,6,7"
 
 # must be in byte
 BENCHIT_KERNEL_CACHELINE_SIZE=64
 
 # must be in Kbytes
 BENCHIT_KERNEL_CACHE_SIZE=512

 #additional Options
 #	-B		Use mmap() files
 #	-D		Use msync(MS_ASYNC) on mmap files
 #	-G		Use msync(MS_SYNC) on mmap files
 #	-c		Include close() in the timing calculations
 #	-e		Include flush (fsync,fflush) in the timing calculations
 #	-j #	Set stride of file accesses to (# * record size). 
 #			The stride read test will read records at this stride.
 #	-J #	Perform a compute delay of this many milliseconds before each I/O operation
 #	-K		Generate some random accesses during the normal testing.
 #	-m		Tells Iozone to use multiple buffers internally
 #	-o		Iozone will open the files with the O_SYNC flag.
 #	-p		This purges the processor cache before each file operation
 #	-Q		Create offset/latency files
 #	-Z		Enable mixing mmap I/O and file I/O.
 #	-+n 	No retests selected.
 #	-+q 	Delay in seconds between tests.
 BENCHIT_KERNEL_OPTIONS="-c -e -p"


 # Describe your own kernel modifications
 BENCHIT_KERNEL_COMMENT="Recordsize=$BENCHIT_KERNEL_RECORDSIZE"


