#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/utilities/skeleton/F77/0/0/simple/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: simple Variant of the Fortran-Skeleton
#####################################################################

 # problem sizes
 BENCHIT_KERNEL_PROBLEMLIST="1,2,3,5-10,11-100/3"

