#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: SX6i 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/tools/environments/SX6i $
# For license details see COPYING in the package base directory
#####################################################################

########################################################################
# FIRST PART: ASSEMBLE COMMAND
########################################################################

execute_cmd="${BENCHIT_KERNELBINARY} ${BENCHIT_KERNELBINARY_ARGS}"

if [ "${BENCHIT_RUN_USE_MPI}" = "1" ]; then
	execute_cmd="mpirun -np ${BENCHIT_NUM_CPUS} ${execute_cmd}"
fi

########################################################################
# SECOND PART: SAVE ENVIRONMENT IF NECESSARY
########################################################################

env | grep BENCHIT | sed -e 's/^\([^=]*\)=\(.*\)$/export \1=\"\2\"/g'> ${BENCHITROOT}/${BENCHIT_KERNELNAME}_env

########################################################################
# THIRD PART: EXECUTE AND CLEANUP
########################################################################

batch_cmd="qsub -c ${BENCHIT_NUM_CPUS}"

if [ -n "${BENCHIT_RUN_REDIRECT_CONSOLE}" ]; then
	batch_cmd="${batch_cmd} -eo -o ${BENCHIT_RUN_REDIRECT_CONSOLE}"
fi

if [ -n "${BENCHIT_RUN_QUEUENAME}" ]; then
	batch_cmd="${batch_cmd} -q ${BENCHIT_RUN_QUEUENAME}"
else
	batch_cmd="${batch_cmd} -q bq6h"
fi

if [ -n "${BENCHIT_RUN_QUEUETIMELIMIT}" ]; then
	qtimelimit=$((${BENCHIT_RUN_QUEUETIMELIMIT}))
else
	# Extend BenchIT timelimit by 10% for queueing
	qtimelimit=$((${BENCHIT_RUN_TIMELIMIT} * 11 / 10))
fi
batch_cmd="${batch_cmd} -lt ${qtimelimit}"

if [ -n "${BENCHIT_RUN_COREDUMPLIMIT}" ]; then
	batch_cmd="${batch_cmd} -lc ${BENCHIT_RUN_COREDUMPLIMIT}"
fi

if [ -n "${BENCHIT_RUN_MAX_MEMORY}" ]; then
	batch_cmd="${batch_cmd} -lm ${BENCHIT_RUN_MAX_MEMORY}"
fi

script="${BENCHITROOT}/temp_script_file_${BENCHIT_KERNELNAME}"
# Remove old script if one exists
rm -f ${script}

# Assemble script for submission to the batch system
echo "#!/bin/sh" > ${script}
echo "cd ${BENCHITROOT}" >> ${script}
echo ". ./${BENCHIT_KERNELNAME}_env" >> ${script}
echo "${execute_cmd}" >> ${script}

if [ "${BENCHIT_RUN_CLEAN}" = "1" ]; then
	echo "rm -f ${BENCHIT_KERNELBINARY}" >> ${script}
	echo "rm ${script}" >> ${script}
fi

chmod +x ${script}

# Submit job to the batch system
batch_cmd="${batch_cmd} ${script}"
if [ "$BENCHIT_RUN_TEST" != "1" ]; then
	${batch_cmd}
else
	echo ${batch_cmd}
	echo "---------------------------------------------------------"
	echo "cat SX6i temporary script:"
	cat ${script}
	echo "---------------------------------------------------------"
fi

