#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/matmul/C/0/0/double_blocked/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Matrix Multiply (C)
#####################################################################

 # Kernel iterates over PROBLEMLIST (size of the blocks)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="10-500/1"
 
 # Kernel uses for each run the same matrix size
 BENCHIT_KERNEL_MATRIX_SIZE=1200

