#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/communication/communicate/C/MPI/0/collective/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: compare the needed time for different MPI communication methodes
#####################################################################
 
 #####
 # attention: don't increase BENCHIT_KERNEL_PROBLEMSIZE_MAX to much, because each process allocates
 #            two arrays with size = BENCHIT_KERNEL_PROBLEMSIZE_MAX * BENCHIT_NUM_CPUS
 #####
 #####
 # left y-axis:  time for one call
 # right y-axis: bandwidth for this call, and thru that the mean bandwidth for all the processes
 #####
 
 # Kernel iterates over PROBLEMLIST (number of floats in the sendarray)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="1024-512000/512"
 

