#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/sort/selsort/C/0/0/simple/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Evaluate time to sort int/float array with selection sort
#####################################################################

 # problem sizes
 BENCHIT_KERNEL_PROBLEMLIST="1-100/3, 100-1000/31, 1000-30000/311"

