#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
#####################################################################

 # Maximum time a kernel may run, in seconds
 # 0 means no timelimit, and the kernel will run until all measurements have
 # completed  
 BENCHIT_RUN_TIMELIMIT=0
 
 # iRODS rescource
 # BENCHIT_IRODS_RESC="" means default resource
 BENCHIT_IRODS_RESC=""
 
 # iRODS data transfer protocol
 # 0 -> TCP; 1 -> RBUDP (iRODS version 2++)
 BENCHIT_IRODS_PROT=0
 
 # Number of threads used for data transfer
 # -1 -> automatically
 #  0 -> no threading
 # >0 -> number of threads
 BENCHIT_IRODS_THREADS=-1

 # Path of temporary saved files (attention to enough space)
 # $KERNELDIR -> path of this Kernel
 BENCHIT_KERNEL_PATH_TEMP=$KERNELDIR

 # Increment size function
 # 0 -> specified size
 # 1 -> ld
 # 2 -> log
 BENCHIT_KERNEL_FILE_SIZE_INC_FUNC=0
 
 # File size of the transfered files
 # *** Only useable if BENCHIT_KERNEL_FILE_SIZE_INC_Func = 0 ***
 # BENCHIT_KERNEL_SMALL_UNIT: "" -> Byte;"K" -> KByte;"M" -> MByte;"G"=GByte
 # BENCHIT_KERNEL_SMALL_SIZE_MIN = 0 -> size of files: 1,2,4,6,8 (INC=2;MAX=8)
 # BENCHIT_KERNEL_SMALL_SIZE_MAX > 1 -> size of files: 1,3,5,7,8 (MIN=1;INC=2;MAX=8)
 BENCHIT_KERNEL_SMALL_UNIT="M"
 BENCHIT_KERNEL_SMALL_SIZE_MIN=0
 BENCHIT_KERNEL_SMALL_SIZE_MAX=10
 BENCHIT_KERNEL_SMALL_SIZE_INC=5
 # *** Only useful if BENCHIT_KERNEL_FILE_SIZE_INC_Func > 0 ***
 # BENCHIT_KERNEL_LARGE_UNIT_*: ""=Byte,"K"=KByte,"M"=MByte,G=GByte
 # BENCHIT_KERNEL_LARGE_SIZE_MIN > 0
 # BENCHIT_KERNEL_LARGE_SIZE_MAX > 0
 BENCHIT_KERNEL_LARGE_UNIT_MIN=""
 BENCHIT_KERNEL_LARGE_SIZE_MIN=1
 BENCHIT_KERNEL_LARGE_UNIT_MAX="G"
 BENCHIT_KERNEL_LARGE_SIZE_MAX=8
 
 # Unit of the file size shown in the plot
 # "" -> Byte;"K" -> KByte;"M" -> MByte;"G"=GByte 
 BENCHIT_KERNEL_VIEW_UNIT_FILESIZE="K"
 
 # Unit of the measured rate shown in the plot 
 # "" -> Byte;"K" -> KByte;"M" -> MByte;"G"=GByte 
 BENCHIT_KERNEL_VIEW_UNIT_RATE="K"
 
 # Number of runs per measurement
 BENCHIT_KERNEL_NUMBER_RUNS=2
 
 # Remove temporary saved files
 # 0 -> remove files after every run
 # 1 -> remove files after the last run of a measurement
 BENCHIT_REMOVE_TEMP=1
 
 # Additional filename string 
 BENCHIT_FILENAME_COMMENT="iRODS"
 
 # Path of the tool time
 BENCHIT_TOOL_TIME=/usr/bin/time
 
 # Don't change the following parameter
 
 BENCHIT_RESULT_NAME="benchit_result_`date "+%d_%m_%Y_%H_%M_%S"`"
 BENCHIT_SPEZIAL_RESULT="$BENCHIT_KERNEL_PATH_TEMP/$BENCHIT_RESULT_NAME"
 BENCHIT_SPEZIAL_SCRIPT="$KERNELDIR/start.sh"

#####################################################################
# Log-History
#
#
#####################################################################
