#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/memory/randomAccess/C/MPI/0/double/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: memory bandwith w. random access
#####################################################################

 BENCHIT_KERNEL_RANDOMACCESS_MEMSIZE=1048576
 BENCHIT_KERNEL_RANDOMACCESS_MEASUREMENTS=1000
 

