#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/memory/latencies/C/0/0/long/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: memory latencies (C)
#####################################################################

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MIN is the minimum
 # of accessed memory (in MByte)                    
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MIN=0.005

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MAX is the maximum
 # of accessed memory (in MByte)                     
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MAX=50

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MEASUREMENTS
 # is the number of measurements              
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MEASUREMENTS=100

 # BENCHIT_KERNEL_MEM_READ_POINTS are explicite sizes of memory to be measured.
 # it overrides the variables above                                      
 #BENCHIT_KERNEL_MEM_READ_POINTS=0.00048828125,0.0009765625,0.001953125,0.00390625,0.0078125,0.015625,0.03125,0.0625,0.125,0.25,0.5,1,2,4,8,16,32,64,128,256

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_STRIDES are the strides
 # to access the memory                                   
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_STRIDES=1,4,16,32,64,128


