#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/matmul/C/SSE2_Intrinsics/0/aligned_m128d/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################

 # Kernel iterates over PROBLEMLIST (one dim of the squared matricies)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="1-75/3,75-250/17,250-1200/31"

