#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/search/patricia/C/0/0/binarytree/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Execution time of Insertion / Searching in a patricia-trie
#         PATRICIA: Practical Algorithm To Retrieve Information
#                   Coded In Alphanumeric
#####################################################################

 # problem sizes
 BENCHIT_KERNEL_PROBLEMLIST="1-200/1"

