#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/gemv/C/OpenMP/0/float/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: C SGEMV kernel
#####################################################################

 # Kernel iterates over PROBLEMLIST (one dim of the squared matricies)
 BENCHIT_KERNEL_PROBLEMLIST="1-1000/1"

