#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
#####################################################################
 
 # iRODS rescource
 # BENCHIT_IRODS_RESC="" means default resource
 BENCHIT_IRODS_RESC=""
 
 # Path of temporary saved files (attention to enough space)
 # $KERNELDIR -> path of this Kernel
 BENCHIT_KERNEL_PATH_TEMP=$KERNELDIR

 # Number of processes for each measurement 
 # BENCHIT_KERNEL_META_MIN = 0 -> number of metadate: 1,2,4,6 (INC=2;MAX=6)
 # BENCHIT_KERNEL_META_MIN > 1 -> number of metadata: 1,3,5,6 (MIN=1;INC=2;MAX=6)
 BENCHIT_KERNEL_PROCESS_MIN=0
 BENCHIT_KERNEL_PROCESS_MAX=10
 # Increment size
 BENCHIT_KERNEL_PROCESS_INC=5
 # Number of requests within a process
 BENCHIT_KERNEL_PROCESS_LOOP=5
 
 # Number of runs per measurement
 BENCHIT_KERNEL_NUMBER_RUNS=1
 
 # Additional filename string 
 BENCHIT_FILENAME_COMMENT="iRODS"
 
 # Path of the tool time
 BENCHIT_TOOL_TIME=/usr/bin/time
 
 # Don't change the following parameter
 
 BENCHIT_RESULT_NAME="benchit_result_`date "+%d_%m_%Y_%H_%M_%S"`"
 BENCHIT_SPEZIAL_RESULT="$BENCHIT_KERNEL_PATH_TEMP/$BENCHIT_RESULT_NAME"
 BENCHIT_SPEZIAL_SCRIPT="$KERNELDIR/start.sh"

#####################################################################
# Log-History
#
#
#####################################################################
