#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/sparse/C/MPI/0/double/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: compare of storage formates for sparse matrices
#####################################################################
 
 # Kernel iterates over PROBLEMLIST (one dim of the squared sparse matrix)
 #BENCHIT_KERNEL_PROBLEMLIST="1,3,6,7,9, 10-100, 100-1000/100, 1000-10000/1000"
 BENCHIT_KERNEL_PROBLEMLIST="10-1400/1"

 # BENCHIT_KERNEL_PERCENT
 BENCHIT_KERNEL_PERCENT=10.0

 # BENCHIT_KERNEL_SEED is the seed value for the random generator
 BENCHIT_KERNEL_SEED=0

 # BENCHIT_KERNEL_INIT define how to initialise the matrix
 # 0 = initRandomMatrix -> create a matrix with random values with a filling rate of BENCHIT_KERNEL_PERCENT
 # 1 = initIDENTITY -> create an identity matrix
 # 2 = initDIAG -> create a band matrix with 3 diagonals
 # 3 = init5PSTAR -> create a 5-point-star matrix for finite elements
 BENCHIT_KERNEL_INIT=0

 # BENCHIT_KERNEL_OUTPUT define the mode of output
 # 0 = FLOPS / IOPS
 # 1 = time for the matrix/sparse vector multiplication
 BENCHIT_KERNEL_OUTPUT=0

 # BENCHIT_KERNEL_WITH_MATxVEC = 0 -> without naive Matrix/Vector multiplication (only Sparse/Vector multiplication)
 # BENCHIT_KERNEL_WITH_MATxVEC = 1 -> with naive Matrix/Vector multiplication
 BENCHIT_KERNEL_WITH_MATxVEC=1

 # BENCHIT_KERNEL_VERIFY = 0 -> don't test for correctness
 # BENCHIT_KERNEL_VERIFY = 1 -> test for correctness of the results of the multiplication (!!! memory/time consuming !!!)
 #                              for this BENCHIT_KERNEL_WITH_MATxVEC=1 is necessary!
 #                              for some compiler an the float/double kernel the results can be differ, even though the results are correct
 BENCHIT_KERNEL_VERIFY=0


